version: 1
validation: sovereign
default_denom: stake
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: extractor
  coins:
  - 20000token
  - 200000000stake
  mnemonic: canal pipe license style master below advance repeat busy buyer chase model
- name: processor
  coins:
  - 10000token
  - 250000000stake
  mnemonic: sunset vault attract friend zero lazy rib hockey rice emotion party visual
- name: manufacturer
  coins:
  - 10000token
  - 250000000stake
  mnemonic: height mechanic crush exit exit position giggle friend critic master erode there
- name: distributor
  coins:
  - 10000token
  - 250000000stake
  mnemonic: vessel dial fun hour easily logic index round sadness assist process grit
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
- name: validator1
  bonded: 200000000stake
- name: validator2
  bonded: 100000000stake