// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: esgobservabilitydemo/esgobservabilitydemo/material_processing.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MaterialProcessing struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialType string `protobuf:"bytes,2,opt,name=materialType,proto3" json:"materialType,omitempty"`
	WaterUse     string `protobuf:"bytes,3,opt,name=waterUse,proto3" json:"waterUse,omitempty"`
	Emissions    string `protobuf:"bytes,4,opt,name=emissions,proto3" json:"emissions,omitempty"`
	Creator      string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MaterialProcessing) Reset()         { *m = MaterialProcessing{} }
func (m *MaterialProcessing) String() string { return proto.CompactTextString(m) }
func (*MaterialProcessing) ProtoMessage()    {}
func (*MaterialProcessing) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a03410dcd4e519e, []int{0}
}
func (m *MaterialProcessing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MaterialProcessing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MaterialProcessing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MaterialProcessing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialProcessing.Merge(m, src)
}
func (m *MaterialProcessing) XXX_Size() int {
	return m.Size()
}
func (m *MaterialProcessing) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialProcessing.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialProcessing proto.InternalMessageInfo

func (m *MaterialProcessing) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MaterialProcessing) GetMaterialType() string {
	if m != nil {
		return m.MaterialType
	}
	return ""
}

func (m *MaterialProcessing) GetWaterUse() string {
	if m != nil {
		return m.WaterUse
	}
	return ""
}

func (m *MaterialProcessing) GetEmissions() string {
	if m != nil {
		return m.Emissions
	}
	return ""
}

func (m *MaterialProcessing) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*MaterialProcessing)(nil), "esgobservabilitydemo.esgobservabilitydemo.MaterialProcessing")
}

func init() {
	proto.RegisterFile("esgobservabilitydemo/esgobservabilitydemo/material_processing.proto", fileDescriptor_1a03410dcd4e519e)
}

var fileDescriptor_1a03410dcd4e519e = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4e, 0x2d, 0x4e, 0xcf,
	0x4f, 0x2a, 0x4e, 0x2d, 0x2a, 0x4b, 0x4c, 0xca, 0xcc, 0xc9, 0x2c, 0xa9, 0x4c, 0x49, 0xcd, 0xcd,
	0xd7, 0xc7, 0x2a, 0x98, 0x9b, 0x58, 0x92, 0x5a, 0x94, 0x99, 0x98, 0x13, 0x5f, 0x50, 0x94, 0x9f,
	0x9c, 0x5a, 0x5c, 0x9c, 0x99, 0x97, 0xae, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xa4, 0x89, 0x4d,
	0xbd, 0x1e, 0x36, 0x41, 0xa5, 0x39, 0x8c, 0x5c, 0x42, 0xbe, 0x50, 0x83, 0x02, 0xe0, 0xe6, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x65, 0xa6, 0x08,
	0x29, 0x71, 0xf1, 0xc0, 0xac, 0x0b, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c,
	0x42, 0x11, 0x13, 0x92, 0xe2, 0xe2, 0x28, 0x07, 0xf1, 0x43, 0x8b, 0x53, 0x25, 0x98, 0xc1, 0xf2,
	0x70, 0xbe, 0x90, 0x0c, 0x17, 0x67, 0x6a, 0x6e, 0x66, 0x71, 0x71, 0x66, 0x7e, 0x5e, 0xb1, 0x04,
	0x0b, 0x58, 0x12, 0x21, 0x20, 0x24, 0xc1, 0xc5, 0x9e, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x5f, 0x24,
	0xc1, 0x0a, 0x96, 0x83, 0x71, 0x9d, 0x7c, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1,
	0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e,
	0x21, 0xca, 0x38, 0xb5, 0x38, 0x5d, 0x17, 0xc5, 0x3f, 0xba, 0xe0, 0x50, 0xa9, 0xc0, 0x1e, 0x58,
	0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0xf0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x27, 0x5a, 0x28, 0x66, 0x01, 0x00, 0x00,
}

func (m *MaterialProcessing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MaterialProcessing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MaterialProcessing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMaterialProcessing(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Emissions) > 0 {
		i -= len(m.Emissions)
		copy(dAtA[i:], m.Emissions)
		i = encodeVarintMaterialProcessing(dAtA, i, uint64(len(m.Emissions)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.WaterUse) > 0 {
		i -= len(m.WaterUse)
		copy(dAtA[i:], m.WaterUse)
		i = encodeVarintMaterialProcessing(dAtA, i, uint64(len(m.WaterUse)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MaterialType) > 0 {
		i -= len(m.MaterialType)
		copy(dAtA[i:], m.MaterialType)
		i = encodeVarintMaterialProcessing(dAtA, i, uint64(len(m.MaterialType)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMaterialProcessing(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMaterialProcessing(dAtA []byte, offset int, v uint64) int {
	offset -= sovMaterialProcessing(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MaterialProcessing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMaterialProcessing(uint64(m.Id))
	}
	l = len(m.MaterialType)
	if l > 0 {
		n += 1 + l + sovMaterialProcessing(uint64(l))
	}
	l = len(m.WaterUse)
	if l > 0 {
		n += 1 + l + sovMaterialProcessing(uint64(l))
	}
	l = len(m.Emissions)
	if l > 0 {
		n += 1 + l + sovMaterialProcessing(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMaterialProcessing(uint64(l))
	}
	return n
}

func sovMaterialProcessing(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMaterialProcessing(x uint64) (n int) {
	return sovMaterialProcessing(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MaterialProcessing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaterialProcessing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MaterialProcessing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MaterialProcessing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaterialType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaterialType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WaterUse", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WaterUse = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Emissions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Emissions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaterialProcessing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaterialProcessing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMaterialProcessing(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMaterialProcessing
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaterialProcessing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMaterialProcessing
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMaterialProcessing
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMaterialProcessing
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMaterialProcessing        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMaterialProcessing          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMaterialProcessing = fmt.Errorf("proto: unexpected end of group")
)
