// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: esgobservabilitydemo/esgobservabilitydemo/v1/raw_material_extraction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "esgobservabilitydemo.esgobservabilitydemo.v1";

/** RawMaterialExtraction defines the RawMaterialExtraction message. */
export interface RawMaterialExtraction {
  id: Long;
  resourceType: string;
  waterUse: string;
  emissions: string;
  creator: string;
}

function createBaseRawMaterialExtraction(): RawMaterialExtraction {
  return { id: Long.UZERO, resourceType: "", waterUse: "", emissions: "", creator: "" };
}

export const RawMaterialExtraction: MessageFns<RawMaterialExtraction> = {
  encode(message: RawMaterialExtraction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (!message.id.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.id.toString());
    }
    if (message.resourceType !== "") {
      writer.uint32(18).string(message.resourceType);
    }
    if (message.waterUse !== "") {
      writer.uint32(26).string(message.waterUse);
    }
    if (message.emissions !== "") {
      writer.uint32(34).string(message.emissions);
    }
    if (message.creator !== "") {
      writer.uint32(42).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawMaterialExtraction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawMaterialExtraction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resourceType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.waterUse = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.emissions = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawMaterialExtraction {
    return {
      id: isSet(object.id) ? Long.fromValue(object.id) : Long.UZERO,
      resourceType: isSet(object.resourceType) ? globalThis.String(object.resourceType) : "",
      waterUse: isSet(object.waterUse) ? globalThis.String(object.waterUse) : "",
      emissions: isSet(object.emissions) ? globalThis.String(object.emissions) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: RawMaterialExtraction): unknown {
    const obj: any = {};
    if (!message.id.equals(Long.UZERO)) {
      obj.id = (message.id || Long.UZERO).toString();
    }
    if (message.resourceType !== "") {
      obj.resourceType = message.resourceType;
    }
    if (message.waterUse !== "") {
      obj.waterUse = message.waterUse;
    }
    if (message.emissions !== "") {
      obj.emissions = message.emissions;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawMaterialExtraction>, I>>(base?: I): RawMaterialExtraction {
    return RawMaterialExtraction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawMaterialExtraction>, I>>(object: I): RawMaterialExtraction {
    const message = createBaseRawMaterialExtraction();
    message.id = (object.id !== undefined && object.id !== null) ? Long.fromValue(object.id) : Long.UZERO;
    message.resourceType = object.resourceType ?? "";
    message.waterUse = object.waterUse ?? "";
    message.emissions = object.emissions ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
